### ISSUE TITLE
IDA 7.4 macOS compatibility

### ISSUE THREAD

**Issue by vit9696** [cseagle/blc#5]
Hello, I tried copying the binaries to ~/.idapro/plugins or IDA installation directory plugins, but for some reason I cannot find the plugin in the menu.

So far I tried 32-bit powerpc ELF binaries and 64-bit x86 Mach-O for a test, both should be supported by Ghidra. Have you tried the plugin on macOS? I removed quarantine attribute the usual way with `xattr -cr`. My IDA installation is 7.4 on 10.15, so far I have not had issues with plugin installation, so I believe the issue should be elsewhere.

**Comment by cseagle** [comment]
Yes, the plugin works fine for me using IDA 7.4 on 10.15.1. The plugin needs to get copied to the proper location within your IDA installation directory. For me this is `/Applications/IDA Pro 7.4/idabin/plugins`

You also need to make sure that you copy the Ghidra/Processors directory into the above directory so that you have `/Applications/IDA Pro 7.4/idabin/plugins/Ghida/Processors/...`

**Comment by vit9696** [comment]
@cseagle thanks for the hint, I indeed forgot to copy Processors directory when I tried loading the plugin from IDA directory, and it does not work from ~/.idapro. This way it works fine.

To be honest, it is a bit unexpected that ~/.idapro way is not working, as it is a pretty standard way to install IDA plugins and configs as advised by Hex-Rays.

I guess the issue could be closed as resolved now.
